server:
  port: 8766

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: zuul

zuul:
  routes:
    api-a:
      path: /a/**
      serviceId: ribbon
    api-b:
      path: /b/**
      serviceId: feign
